#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() { [[ -t 1 ]] || return 0; if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi; }

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() { _clear; _STAGE_INDEX=$((_STAGE_INDEX + 1)); printf '\n%s%s▸ Stage %s/%s · %s%s\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"; }
say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"; printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if command -v wslview >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then open "$url"
    else warn "couldn't open browser — visit manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open browser — visit manually: $url"
}

pause() { printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"; read -r _ || true; }
confirm() { local r=""; printf '  %s? %s [y/N] ' "$YELLOW" "$1"; read -r r || true; [[ "$r" =~ ^[Yy] ]]; }

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi
  read -rs input || true; printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"; tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

_ssm_put() {
  local name="$1" value="$2" type="${3:-String}"
  if aws ssm put-parameter --name "$name" --value "$value" --type "$type" --overwrite >/dev/null 2>&1; then
    printf '  %s✓ SSM%s %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("SSM $name")
    warn "Could not write to SSM — set it manually later"
  fi
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_ENV="${ROOT_DIR}/backend/.env"
FRONTEND_ENV="${ROOT_DIR}/frontend/.env"

TOTAL_STAGES=6

banner "MemoryVault — Supabase setup"

# ── Stage 1: Create Supabase project ──────────────────────────────────────
stage "Create Supabase project"
say "We'll create a new Supabase project for MemoryVault."
open_url "https://supabase.com/dashboard/new/_"
say ""
step "Click 'New project'"
step "Name it: memoryvault  (or any name you like)"
step "Choose a strong database password — save it somewhere safe"
step "Select your region (pick the same region as your AWS stack: us-east-1 = US East)"
step "Click 'Create new project' and wait for provisioning (~2 minutes)"
pause "Press Enter once the project is fully provisioned (green status)."

# ── Stage 2: Capture API keys ─────────────────────────────────────────────
stage "API keys"
say "We need four values from the API settings page."
open_url "https://supabase.com/dashboard/project/_/settings/api"
say ""
step "Copy the 'Project URL'  (looks like https://xxxx.supabase.co)"
ask SUPABASE_URL "Paste Project URL:"
say ""
step "Copy the 'anon public' key under 'Project API keys'"
ask SUPABASE_ANON_KEY "Paste anon key:"
say ""
step "Click 'Reveal' on the 'service_role' key and copy it"
note "  Keep this secret — it bypasses Row Level Security"
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste service_role key:"
say ""
step "Scroll down to 'JWT Settings' → copy the 'JWT Secret'"
ask_secret SUPABASE_JWT_SECRET "Paste JWT secret:"

# ── Stage 3: Capture Supavisor DB connection string ───────────────────────
stage "Database connection string (Supavisor)"
say "The backend connects to Postgres via Supavisor (connection pooler)."
open_url "https://supabase.com/dashboard/project/_/settings/database"
say ""
step "Scroll to 'Connection string'"
step "Select mode: 'Session' (not Transaction — required for Mangum/Lambda)"
step "Copy the connection string"
note "  It looks like: postgresql://postgres.xxxx:[PASSWORD]@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
note "  Replace [YOUR-PASSWORD] with the database password you set in stage 1"
ask_secret SUPABASE_DB_URL "Paste the Supavisor session-mode connection string (with password filled in):"

# ── Stage 4: Update AWS Secrets Manager with the real DB URL ──────────────
stage "Update AWS Secrets Manager"
say "The CloudFormation stack created a placeholder Secrets Manager entry."
say "We'll update it now with the real Supabase connection string."
say ""

# Resolve stack name from SSM or default
STACK_NAME=$(aws ssm get-parameter --name /memoryvault/deploy/stack-name \
  --query "Parameter.Value" --output text 2>/dev/null || echo "memoryvault")
AWS_REGION=$(aws ssm get-parameter --name /memoryvault/deploy/region \
  --query "Parameter.Value" --output text 2>/dev/null || echo "us-east-1")

SECRET_ID="${STACK_NAME}/supabase-connection-string"
say "Writing to Secrets Manager: ${SECRET_ID}"

if aws secretsmanager put-secret-value \
  --region "${AWS_REGION}" \
  --secret-id "${SECRET_ID}" \
  --secret-string "{\"connection_string\":\"${SUPABASE_DB_URL}\"}" >/dev/null 2>&1; then
  printf '  %s✓ Secrets Manager updated%s\n' "$GREEN" "$RESET"
else
  warn "Could not update Secrets Manager. Run this manually:"
  printf '    aws secretsmanager put-secret-value \\\n'
  printf '      --secret-id "%s" \\\n' "${SECRET_ID}"
  printf '      --secret-string '"'"'{"connection_string":"<YOUR_URL>"}'"'"'\n'
  SKIPPED+=("Secrets Manager ${SECRET_ID}")
fi

# ── Stage 5: Write values to SSM Parameter Store ──────────────────────────
stage "SSM Parameter Store"
say "Storing non-secret values in SSM so any machine with AWS credentials"
say "can connect to the right Supabase project."
say ""
_ssm_put "/memoryvault/supabase/url"              "${SUPABASE_URL}"
_ssm_put "/memoryvault/supabase/anon-key"         "${SUPABASE_ANON_KEY}"
_ssm_put "/memoryvault/supabase/service-role-key" "${SUPABASE_SERVICE_ROLE_KEY}" "SecureString"
_ssm_put "/memoryvault/supabase/jwt-secret"       "${SUPABASE_JWT_SECRET}"       "SecureString"

# ── Stage 6: Write local .env files ───────────────────────────────────────
stage "Local .env files"
say "Writing values to local .env files for development."
note "Both files are gitignored — they will never be committed."
say ""

say "→ backend/.env"
ENV_FILE="${BACKEND_ENV}"
write_env SUPABASE_URL              "${SUPABASE_URL}"
write_env SUPABASE_SERVICE_ROLE_KEY "${SUPABASE_SERVICE_ROLE_KEY}"
write_env SUPABASE_JWT_SECRET       "${SUPABASE_JWT_SECRET}"
write_env SUPABASE_DB_URL           "${SUPABASE_DB_URL}"

say ""
say "→ frontend/.env"
ENV_FILE="${FRONTEND_ENV}"
write_env VITE_API_BASE_URL   "http://localhost:8000"
write_env VITE_SUPABASE_URL   "${SUPABASE_URL}"
write_env VITE_SUPABASE_ANON_KEY "${SUPABASE_ANON_KEY}"

say ""
say "You're ready to implement issue 03."
say "Run the SQL migrations next: see .scratch/memoryvault-mvp/issues/03-supabase-schema-auth.md"

finish
